### PR TITLE
Attribute passthrough

### PR DESCRIPTION
**Pull request by artnez**
Adds support for passthrough attributes on style components. Proposed in #32.

### CODE REVIEW

**Comment by artnez** [comment]
At first I figured using Chromium as a source for the CSS whitelist was the best option. Browsers have to cover a wide breadth after all. Programmatically extracting the actual properties was more trouble than it was worth.

So instead I wrote a simple scraping utility to fetch the properties from [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference). That list seems to be updated pretty consistently and is easy enough to parse.

**Comment by meyer** [comment]
@artnez ah, good idea pulling from MDN.

**Comment by artnez** [comment]
Unfortunately that MDN page was inconsistent as well :( Using all [MDN pages tagged as `CSS Property`](https://developer.mozilla.org/en-US/docs/tag/CSS%20Property) worked about better.

If this PR gets approved I'm happy to manually amend this list with missing things. Worst case we can continue amending the list over time.

**Comment by artnez** [comment]
Cleaned up history to make reviewing this easier.

**Comment by artnez** [comment]
PR is growing a bit stale. Anything I can do to help? FWIW we've been using it production for a while now.

**Comment by meyer** [comment]
@artnez sorry for the insane reply time. We’ve discussed this and have decided that it’s not a route we want to go. Part of what’s great about jsxstyle (to me) is that it’s very low on magic. Style props and component props trade places and that’s it. It’s always crystal clear what is and is not a style prop. Once we move both style props and non-style props to the top level, that distinction disappears.

All that said, this feature could be very easily added with a simple `babel` transform. You’d be able to avoid shipping a whitelist of CSS prop strings to the client and the end result would be the same. If you’re curious, I can send you the rough transform idea.

Again, my apologies for the extremely late response.

On a related note, the MDN folks have just pushed their dataset to NPM: https://github.com/mdn/data. Should remove the need to scrape data from the MDN site.

**Comment by artnez** [comment]
Hey no problem. Thanks for considering it.

We've found this approach to be a great for our workflow, but I understand why it's not suited at the library level. If there's a way you could make `getStyleFromProps()` pluggable then we could migrate our code into an extension/plugin for JSXStyle. Otherwise we're content with maintaining our own fork. We haven't had to touch it since December and probably won't be doing so for a long time; it just works. And thanks for the MDN data link. We'll definitely use that.

There is one thing in this PR I suggest you keep: `GlobalStylesheets.reset()`. It made writing tests a lot easier because the generated class names (`jsxstyle1`, `jsxstyle2`, etc) didn't depend on the order in which you define the tests.

**Pull request closed without merging**
